#!/bin/sh

BRANCH_NAME=$(git branch | grep "*"| awk '{print $2 }' );
echo $BRANCH_NAME;
if [   $BRANCH_NAME ] 	
then 
	git add .; 
	echo "$(git commit -m "Stone-Gate" && sleep 4)" ;
	echo "push to $BRANCH_NAME ";
	echo "$(git push origin $BRANCH_NAME)";
else 
	echo "no git " ;
	rm ~/darkh.log/git.log ;
fi 


