#!/bin/sh

BRANCH_NAME=$(git branch | grep "*"| awk '{print $2 }' >& ~/darkh.log/git.log );

if ! grep "fatal" ~/darkh.log/git.log 
then 
	git add .; 
	echo "$(git commit -m "Stone-Gate" && sleep 4)" ;
	echo "$(git push origin $BRANCH_NAME)";
else 
	echo "no git " ;
	rm ~/darkh.log/git.log ;
fi 


